channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - muscle=5.1
  - fasttree=2.1.11 
  - r-base=4.2.2
  - r-renv=0.16.0
  - bioconductor-biocversion=3.16.0
  - r-rmarkdown=2.20
  - r-ggpubr=0.6.0        
  - r-rstatix=0.7.2       
  - r-dplyr=1.1.0         
  - r-ggprism=1.0.4       
  - r-scales=1.2.1        
  - r-ggplot2=3.4.1       
  - r-vegan=2.6_4        
  - r-data.table=1.14.8   
  - bioconductor-biostrings=2.66.0   
  - bioconductor-ggtree=3.6.0        
  - bioconductor-treeio=1.22.0       
  - r-tidyr=1.3.0  
  - r-ggVennDiagram=1.2.2
  - r-viridislite=0.4.1
  - r-kableextra=1.3.4
  - r-stringdist=0.9.10
  - r-jsonlite=1.8.4
